// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByzCJQtRqjgD5p3AiemPAK1tyXnqlCGdY',
    appId: '1:1039899503731:android:d0df50ebc708b338280e06',
    messagingSenderId: '1039899503731',
    projectId: 'shop-app-78398',
    databaseURL: 'https://shop-app-78398-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-78398.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0-Yqo2MFsYw6yYFSs7G0J35ms5NAkUrU',
    appId: '1:1039899503731:ios:6ea8498f99c16744280e06',
    messagingSenderId: '1039899503731',
    projectId: 'shop-app-78398',
    databaseURL: 'https://shop-app-78398-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-78398.appspot.com',
    iosClientId:
        '1039899503731-pmldoe97r8gmvpbm78plut9m0namsg9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.myShopApp',
  );
}
